feature: revert redundant

diff --git a/.github/workflows/auto-merge.yml b/.github/workflows/auto-merge.yml
--- a/.github/workflows/auto-merge.yml
+++ b/.github/workflows/auto-merge.yml
@@ -20,29 +20,29 @@ jobs:
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
 
-      - name: Return error
+      # - name: Return error
+      #   run: |
+      #     echo "Error: Merge conflict detected"
+      #     exit 1
+
+      - name: Merge main into develop
         run: |
-          echo "Error: Merge conflict detected"
-          exit 1
+          git checkout develop
+          if ! git merge main; then
+            echo "Error: Merge conflict detected"
+            exit 1
+          fi
+          git push origin develop
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      # - name: Merge main into develop
-      #   run: |
-      #     git checkout develop
-      #     if ! git merge main; then
-      #       echo "Error: Merge conflict detected"
-      #       exit 1
-      #     fi
-      #     git push origin develop
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      # - name: Reset to nearest commit of develop and checkout to main
-      #   if: failure()
-      #   run: |
-      #     git reset --hard origin/develop
-      #     git checkout main
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Reset to nearest commit of develop and checkout to main
+        if: failure()
+        run: |
+          git reset --hard origin/develop
+          git checkout main
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Create a pull request if fail
         if: failure()
